name: stock_predictions
channels:
  - anaconda
  - defaults
dependencies:
  - appdirs=1.4.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - cryptography=38.0.4
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - fftw=3.3.9
  - icc_rt=2022.1.0
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - libffi=3.4.2
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numexpr=2.8.4
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.5.2
  - pip=22.3.1
  - pooch=1.4.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - pytz=2022.7
  - requests=2.28.1
  - scipy=1.10.0
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - urllib3=1.26.14
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.2.2
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - zipp=3.11.0
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - beautifulsoup4==4.11.1
      - cachetools==5.3.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - flatbuffers==23.1.21
      - fonttools==4.38.0
      - frozendict==2.3.4
      - gast==0.4.0
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.1
      - h5py==3.8.0
      - html5lib==1.1
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - libclang==15.0.6.1
      - lxml==4.9.2
      - markdown==3.4.1
      - matplotlib==3.6.3
      - multitasking==0.0.11
      - numpy==1.24.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pillow==9.4.0
      - protobuf==3.19.6
      - pyarrow==10.0.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyparsing==3.0.9
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.1
      - sklearn==0.0.post1
      - soupsieve==2.3.2.post1
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - typing-extensions==4.4.0
      - webencodings==0.5.1
      - wrapt==1.14.1
      - yfinance==0.2.4
      - flask==2.2.2

